### ISSUE TITLE
测试了效率比较低下i5 11代主机 16G内村 1秒存取一万次，与redis 10万次相差太远了。楼主有办法能提高速度吗

### ISSUE THREAD

**Issue by tyyfp** [mataness/StackExchange.Redis.MultiplexerPool#1]
测试了效率比较低下i5 11代主机 16G内村 1秒存取一万次，与redis 10万次相差太远了。楼主有办法能提高速度吗。试了别人写的，速度还比你快点。你的代码看着挺牛的

**Comment by tyyfp** [comment]
还不如单实例快，写这个东西的意义在哪呢

**Comment by tyyfp** [comment]
好像才5000 模拟并行10个线程 进行测试

**Comment by mataness** [comment]
English please
